//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 12:57:21 AM WAT 
//


package com.johnny.webservice.schema.parlayx.ussd.notification.v1_0.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.parlayx.ussd.notification.v1_0.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NotifyUssdReception_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdReception");
    private final static QName _NotifyUssdReceptionResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdReceptionResponse");
    private final static QName _NotifyUssdAbort_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdAbort");
    private final static QName _NotifyUssdAbortResponse_QNAME = new QName("http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", "notifyUssdAbortResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.parlayx.ussd.notification.v1_0.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyUssdReception }
     * 
     */
    public NotifyUssdReception createNotifyUssdReception() {
        return new NotifyUssdReception();
    }

    /**
     * Create an instance of {@link NotifyUssdReceptionResponse }
     * 
     */
    public NotifyUssdReceptionResponse createNotifyUssdReceptionResponse() {
        return new NotifyUssdReceptionResponse();
    }

    /**
     * Create an instance of {@link NotifyUssdAbort }
     * 
     */
    public NotifyUssdAbort createNotifyUssdAbort() {
        return new NotifyUssdAbort();
    }

    /**
     * Create an instance of {@link NotifyUssdAbortResponse }
     * 
     */
    public NotifyUssdAbortResponse createNotifyUssdAbortResponse() {
        return new NotifyUssdAbortResponse();
    }

    /**
     * Create an instance of {@link NamedParameterList }
     * 
     */
    public NamedParameterList createNamedParameterList() {
        return new NamedParameterList();
    }

    /**
     * Create an instance of {@link NamedParameter }
     * 
     */
    public NamedParameter createNamedParameter() {
        return new NamedParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdReception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyUssdReception }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdReception")
    public JAXBElement<NotifyUssdReception> createNotifyUssdReception(NotifyUssdReception value) {
        return new JAXBElement<NotifyUssdReception>(_NotifyUssdReception_QNAME, NotifyUssdReception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdReceptionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyUssdReceptionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdReceptionResponse")
    public JAXBElement<NotifyUssdReceptionResponse> createNotifyUssdReceptionResponse(NotifyUssdReceptionResponse value) {
        return new JAXBElement<NotifyUssdReceptionResponse>(_NotifyUssdReceptionResponse_QNAME, NotifyUssdReceptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbort }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbort }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdAbort")
    public JAXBElement<NotifyUssdAbort> createNotifyUssdAbort(NotifyUssdAbort value) {
        return new JAXBElement<NotifyUssdAbort>(_NotifyUssdAbort_QNAME, NotifyUssdAbort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbortResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyUssdAbortResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/parlayx/ussd/notification/v1_0/local", name = "notifyUssdAbortResponse")
    public JAXBElement<NotifyUssdAbortResponse> createNotifyUssdAbortResponse(NotifyUssdAbortResponse value) {
        return new JAXBElement<NotifyUssdAbortResponse>(_NotifyUssdAbortResponse_QNAME, NotifyUssdAbortResponse.class, null, value);
    }

}
