//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.28 at 12:57:21 AM WAT 
//


package com.johnny.webservice.schema.osg.ussd.notification_manager.v1_0.local;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csapi.schema.osg.ussd.notification_manager.v1_0.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StartUSSDNotification_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "startUSSDNotification");
    private final static QName _StartUSSDNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "startUSSDNotificationResponse");
    private final static QName _StopUSSDNotification_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "stopUSSDNotification");
    private final static QName _StopUSSDNotificationResponse_QNAME = new QName("http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", "stopUSSDNotificationResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csapi.schema.osg.ussd.notification_manager.v1_0.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StartUSSDNotification }
     * 
     */
    public StartUSSDNotification createStartUSSDNotification() {
        return new StartUSSDNotification();
    }

    /**
     * Create an instance of {@link StartUSSDNotificationResponse }
     * 
     */
    public StartUSSDNotificationResponse createStartUSSDNotificationResponse() {
        return new StartUSSDNotificationResponse();
    }

    /**
     * Create an instance of {@link StopUSSDNotification }
     * 
     */
    public StopUSSDNotification createStopUSSDNotification() {
        return new StopUSSDNotification();
    }

    /**
     * Create an instance of {@link StopUSSDNotificationResponse }
     * 
     */
    public StopUSSDNotificationResponse createStopUSSDNotificationResponse() {
        return new StopUSSDNotificationResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartUSSDNotification }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StartUSSDNotification }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "startUSSDNotification")
    public JAXBElement<StartUSSDNotification> createStartUSSDNotification(StartUSSDNotification value) {
        return new JAXBElement<StartUSSDNotification>(_StartUSSDNotification_QNAME, StartUSSDNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartUSSDNotificationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StartUSSDNotificationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "startUSSDNotificationResponse")
    public JAXBElement<StartUSSDNotificationResponse> createStartUSSDNotificationResponse(StartUSSDNotificationResponse value) {
        return new JAXBElement<StartUSSDNotificationResponse>(_StartUSSDNotificationResponse_QNAME, StartUSSDNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopUSSDNotification }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StopUSSDNotification }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "stopUSSDNotification")
    public JAXBElement<StopUSSDNotification> createStopUSSDNotification(StopUSSDNotification value) {
        return new JAXBElement<StopUSSDNotification>(_StopUSSDNotification_QNAME, StopUSSDNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StopUSSDNotificationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StopUSSDNotificationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.csapi.org/schema/osg/ussd/notification_manager/v1_0/local", name = "stopUSSDNotificationResponse")
    public JAXBElement<StopUSSDNotificationResponse> createStopUSSDNotificationResponse(StopUSSDNotificationResponse value) {
        return new JAXBElement<StopUSSDNotificationResponse>(_StopUSSDNotificationResponse_QNAME, StopUSSDNotificationResponse.class, null, value);
    }

}
